In [1]:
import os
os.getcwd()

'c:\\Users\\user\\Downloads\\인사이콘'

In [2]:
import pandas as pd

df = pd.read_csv("Insight-Financial-Transaction-2024H1.csv")

In [3]:
print(df.columns)

Index(['ACCOUNT_ID', 'CARD_ID', 'TRANSACTION_ID', 'GROSS_TRANSACTION_AMOUNT',
       'TRANSACTION_DATE', 'TRANSACTION_TYPE', 'TRANSACTION_STATE',
       'TRANSACTION_CITY', 'MERCHANT_STATE', 'MERCHANT_CITY',
       'MERCHANT_CATEGORY_LEVEL_1', 'MERCHANT_CATEGORY_LEVEL_2',
       'MERCHANT_CATEGORY_LEVEL_3', 'TRANSACTION_DESCRIPTION', 'CARD_TYPE',
       'CARD_HOLDER_STATE', 'CARD_HOLDER_CITY', 'CARD_HOLDER_GENERATION',
       'CARD_HOLDER_TOTAL_TRANSACTION_COUNT', 'CARD_HOLDER_TOTAL_SPEND',
       'CARD_HOLDER_AVERAGE_LTM_SPEND',
       'CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT', 'CARD_HOLDER_VINTAGE',
       'CARD_PRESENT_INDICATOR', 'MERCHANT_ID', 'MERCHANT_NAME',
       'SHOPPER_CLASSIFICATION'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4777635 entries, 0 to 4777634
Data columns (total 27 columns):
 #   Column                                     Dtype
---  ------                                     -----
 0   ACCOUNT_ID                                 object
 1   CARD_ID                                    object
 2   TRANSACTION_ID                             object
 3   GROSS_TRANSACTION_AMOUNT                   float64
 4   TRANSACTION_DATE                           object
 5   TRANSACTION_TYPE                           object
 6   TRANSACTION_STATE                          object
 7   TRANSACTION_CITY                           object
 8   MERCHANT_STATE                             object
 9   MERCHANT_CITY                              object
 10  MERCHANT_CATEGORY_LEVEL_1                  object
 11  MERCHANT_CATEGORY_LEVEL_2                  object
 12  MERCHANT_CATEGORY_LEVEL_3                  object
 13  TRANSACTION_DESCRIPTION                    object
 14  CARD_TYPE                                  object
 15  CARD_HOLDER_STATE                          object
 16  CARD_HOLDER_CITY                           object
 17  CARD_HOLDER_GENERATION                     object
 18  CARD_HOLDER_TOTAL_TRANSACTION_COUNT        int64
 19  CARD_HOLDER_TOTAL_SPEND                    float64
 20  CARD_HOLDER_AVERAGE_LTM_SPEND              float64
 21  CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT  float64
 22  CARD_HOLDER_VINTAGE                        int64
 23  CARD_PRESENT_INDICATOR                     object
 24  MERCHANT_ID                                int64
 25  MERCHANT_NAME                              object
 26  SHOPPER_CLASSIFICATION                     int64
dtypes: float64(4), int64(4), object(19)
memory usage: 984.2+ MB

In [8]:
df.select_dtypes(include=['int64', 'float64'])

,GROSS_TRANSACTION_AMOUNT,CARD_HOLDER_TOTAL_TRANSACTION_COUNT,CARD_HOLDER_TOTAL_SPEND,CARD_HOLDER_AVERAGE_LTM_SPEND,CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT,CARD_HOLDER_VINTAGE,MERCHANT_ID,SHOPPER_CLASSIFICATION
0,0.99,443,8452.70,511.77,26.25,29,112,0
1,22.76,3382,115654.41,NaN,NaN,87,214,2
2,8.84,1999,48756.32,2400.99,100.33,25,58,0
3,8.78,449,10444.67,NaN,NaN,26,37,0
4,18.01,551,16220.59,1513.71,51.27,10,522,0
...,...,...,...,...,...,...,...,...
4777630,8.99,2235,69397.77,1559.00,47.00,44,250,0
4777631,3.94,1220,25270.58,1285.92,65.58,17,37,0
4777632,2.07,10412,273787.83,3416.36,114.58,87,1351,2
4777633,31.33,3865,177495.83,1529.61,62.58,83,87,2
4777634,13.33,251,15483.71,267.90,4.58,82,37,2

In [17]:
cols = [
    'GROSS_TRANSACTION_AMOUNT',
    'CARD_HOLDER_TOTAL_TRANSACTION_COUNT',
    'CARD_HOLDER_TOTAL_SPEND',
    'CARD_HOLDER_AVERAGE_LTM_SPEND',
    'CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT'
]

df[cols].describe()

,GROSS_TRANSACTION_AMOUNT,CARD_HOLDER_TOTAL_TRANSACTION_COUNT,CARD_HOLDER_TOTAL_SPEND,CARD_HOLDER_AVERAGE_LTM_SPEND,CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT
count,4.777635e+06,4.777635e+06,4.777635e+06,4.159079e+06,4.159079e+06
mean,4.247520e-18,1.475329e-18,8.566427e-19,1.148054e-18,-8.200386e-19
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-8.893757e-01,-2.209845e-02,-2.159798e-02,-2.378128e-02,-2.577803e-02
25%,-5.385738e-01,-2.189225e-02,-2.158720e-02,-2.345040e-02,-2.425479e-02
50%,-2.043819e-01,-2.171478e-02,-2.157723e-02,-2.324297e-02,-2.338658e-02
75%,2.653470e-01,-2.139843e-02,-2.155869e-02,-2.296107e-02,-2.231168e-02
max,6.208976e+02,4.636937e+01,4.636937e+01,4.326216e+01,4.326211e+01

In [16]:
num_cols = df.select_dtypes(include='number').columns

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df[num_cols] = scaler.fit_transform(df[num_cols]) 

print(df[num_cols])

         GROSS_TRANSACTION_AMOUNT  CARD_HOLDER_TOTAL_TRANSACTION_COUNT  \
0                       -0.824265                            -0.021981
1                        0.622128                            -0.021199
2                       -0.302713                            -0.021567
3                       -0.306699                            -0.021980
4                        0.306540                            -0.021952
...                           ...                                  ...
4777630                 -0.292747                            -0.021504
4777631                 -0.628267                            -0.021774
4777632                 -0.752510                            -0.019329
4777633                  1.191517                            -0.021071
4777634                 -0.004398                            -0.022032

         CARD_HOLDER_TOTAL_SPEND  CARD_HOLDER_AVERAGE_LTM_SPEND  \
0                      -0.021595                      -0.023651
1                      -0.021555                            NaN
2                      -0.021580                      -0.023170
3                      -0.021594                            NaN
4                      -0.021592                      -0.023396
...                          ...                            ...
4777630                -0.021572                      -0.023385
4777631                -0.021589                      -0.023454
4777632                -0.021496                      -0.022912
4777633                -0.021532                      -0.023392
4777634                -0.021592                      -0.023714

         CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT  CARD_HOLDER_VINTAGE  \
0                                        -0.024688            -0.336748
1                                              NaN             2.056110
2                                        -0.021492            -0.501773
3                                              NaN            -0.460517
4                                        -0.023609            -1.120616
...                                            ...                  ...
4777630                                  -0.023793             0.282094
4777631                                  -0.022991            -0.831823
4777632                                  -0.020877             2.056110
4777633                                  -0.023121             1.891085
4777634                                  -0.025624             1.849829

         MERCHANT_ID  SHOPPER_CLASSIFICATION
0          -0.200224               -0.536999
1           0.053783                2.029043
2          -0.334698               -0.536999
3          -0.386993               -0.536999
4           0.820783               -0.536999
...              ...                     ...
4777630     0.143432               -0.536999
4777631    -0.386993               -0.536999
4777632     2.885210                2.029043
4777633    -0.262480                2.029043
4777634    -0.386993                2.029043

[4777635 rows x 8 columns]

In [7]:
df.describe()

,GROSS_TRANSACTION_AMOUNT,CARD_HOLDER_TOTAL_TRANSACTION_COUNT,CARD_HOLDER_TOTAL_SPEND,CARD_HOLDER_AVERAGE_LTM_SPEND,CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT,CARD_HOLDER_VINTAGE,MERCHANT_ID,SHOPPER_CLASSIFICATION
count,4.777635e+06,4.777635e+06,4.777635e+06,4.159079e+06,4.159079e+06,4.777635e+06,4.777635e+06,4.777635e+06
mean,1.339620e+01,8.305818e+04,5.813551e+07,9.336455e+04,5.983867e+02,3.716238e+01,1.924028e+02,4.185426e-01
std,1.505123e+01,3.758462e+06,2.691710e+09,3.925885e+06,2.317426e+04,2.423880e+01,4.015644e+02,7.794104e-01
min,1.000000e-02,2.000000e+00,1.744000e+01,1.990000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.290000e+00,7.770000e+02,2.902174e+04,1.300990e+03,3.630000e+01,1.700000e+01,3.000000e+00,0.000000e+00
50%,1.032000e+01,1.444000e+03,5.586240e+04,2.115320e+03,5.642000e+01,3.000000e+01,3.700000e+01,0.000000e+00
75%,1.739000e+01,2.633000e+03,1.057832e+05,3.222040e+03,8.133000e+01,5.300000e+01,1.550000e+02,0.000000e+00
max,9.358670e+03,1.743606e+08,1.248710e+11,1.699356e+08,1.003166e+06,8.800000e+01,3.393000e+03,2.000000e+00

In [11]:
df.isnull().sum()

ACCOUNT_ID                                    132703
CARD_ID                                            0
TRANSACTION_ID                                     0
GROSS_TRANSACTION_AMOUNT                           0
TRANSACTION_DATE                                   0
TRANSACTION_TYPE                                   1
TRANSACTION_STATE                             121664
TRANSACTION_CITY                              143825
MERCHANT_STATE                                583358
MERCHANT_CITY                                 702539
MERCHANT_CATEGORY_LEVEL_1                    1293772
MERCHANT_CATEGORY_LEVEL_2                    1293772
MERCHANT_CATEGORY_LEVEL_3                    1293982
TRANSACTION_DESCRIPTION                         5463
CARD_TYPE                                          0
CARD_HOLDER_STATE                              19430
CARD_HOLDER_CITY                               19430
CARD_HOLDER_GENERATION                         57808
CARD_HOLDER_TOTAL_TRANSACTION_COUNT                0
CARD_HOLDER_TOTAL_SPEND                            0
CARD_HOLDER_AVERAGE_LTM_SPEND                 618556
CARD_HOLDER_AVERAGE_LTM_TRANSACTION_COUNT     618556
CARD_HOLDER_VINTAGE                                0
CARD_PRESENT_INDICATOR                             0
MERCHANT_ID                                        0
MERCHANT_NAME                                      0
SHOPPER_CLASSIFICATION                             0
dtype: int64